// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopLibrary.Modele;

#nullable disable

namespace PetShopLibrary.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20230915100258_InitPetShop")]
    partial class InitPetShop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("PetShopLibrary.Modele.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PanierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromotionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieID");

                    b.HasIndex("PanierId");

                    b.HasIndex("PromotionID");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("pourcentage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Panier", b =>
                {
                    b.HasOne("PetShopLibrary.Modele.Client", "Client")
                        .WithOne("Panier")
                        .HasForeignKey("PetShopLibrary.Modele.Panier", "ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Produit", b =>
                {
                    b.HasOne("PetShopLibrary.Modele.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopLibrary.Modele.Panier", "Panier")
                        .WithMany("Produits")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopLibrary.Modele.Promotion", "Promotion")
                        .WithMany("Produits")
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Panier");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Client", b =>
                {
                    b.Navigation("Panier");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Panier", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("PetShopLibrary.Modele.Promotion", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
